### ISSUE TITLE
flutter get 报错

### ISSUE THREAD

**Issue by tqhsgithub** [crazecoder/flutter_pgyer#7]
The plugin `flutter_pgyer` doesn't have a main class defined in /Users/tuqinghai/.pub-cache/hosted/pub.flutter-io.cn/flutter_pgyer-1.0.1/android/src/main/java/com/crazecoder/flutter/pgyer/FlutterPgyerPlugin.java or /Users/tuqinghai/.pub-cache/hosted/pub.flutter-io.cn/flutter_pgyer-1.0.1/android/src/main/kotlin/com/crazecoder/flutter/pgyer/FlutterPgyerPlugin.kt. This is likely to due to an incorrect `androidPackage: com.crazecoder.flutter.pgyer` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 

[✓] Flutter (Channel master, 1.19.0-4.0.pre.47, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
[✓] Connected device (2 available)

**Comment by isslii** [comment]
+1

flutter packages get

Running "flutter pub get" in flutter_factory...                     4.8s
The plugin `flutter_pgyer` doesn't have a main class defined in
/code/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/flutter_pgyer-1.0.1/android/src/main/java/com/crazecoder/flutter/pgyer/FlutterPgyerPlugin.java or
/code/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/flutter_pgyer-1.0.1/android/src/main/kotlin/com/crazecoder/flutter/pgyer/FlutterPgyerPlugin.kt. This is likely to due to an incorrect
`androidPackage: com.crazecoder.flutter.pgyer` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.


[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.1 19B2093, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 4.0)
[!] VS Code (version 1.49.3)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)
